# version: '3.5'

# services:
#   db:
#     image: postgres
#     restart: always
#     env_file:
#     - docker.env
#     container_name: postgres
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     container_name: nest-pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#     ports:
#       - '5050:80'
#     depends_on:
#       - db
version: "3"
services:
  postgres:
    container_name: postgres2
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
 
networks:
  postgres:
    driver: bridge